### ISSUE TITLE
[Unity] Bug: loader.mjs cannot load packages which container dot in their names

### ISSUE THREAD

**Issue by zhihesoft** [puerts/puerts-commonjs#2]
packages like xxx.yyy.zzz cannot be loaded by *puerts-commonjs/loader.mjs*
it will be failed with *"cannot find module xxx.yyy.zzz"*

puerts-commonjs/loader.mjs line 38
```
function getFileExtension(filepath) {
    let last = filepath.split('/').pop();
    let frags = last.split('.');
    if (frags.length > 1) {
        return frags.pop();
    }
}
```
### if *filepath* is a dir, getFileExtension should return undefine

**Comment by zombieyang** [comment]
could you summit a PR to fix?

**Comment by zhihesoft** [comment]
### pr is submit
for i dont know how to check a filepath is dir or file in PUERTS system,
so just move the simple filepath check to the end of the check list.

**Comment by zombieyang** [comment]
thanks for contribution
